source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'slim'
gem 'devise'
gem 'sass-rails', '~> 4.0.0'
gem 'foundation-rails', '5.2.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'puma'
gem 'pg'

group :development do
  gem 'capistrano'
  gem 'capistrano-rvm'
  gem 'capistrano-rails',   '~> 1.1', require: false
  gem 'capistrano-bundler', '~> 1.1', require: false
end

group :development, :test do
	gem 'sqlite3'
  gem 'rspec-rails', '~> 3.0.0.beta'
  gem "factory_girl_rails", "~> 4.0"
  gem 'shoulda'
  gem 'capybara'
  gem 'cucumber-rails', :require => false
  gem "selenium-webdriver", "~> 2.41.0"
end
